Sentence me har word ko ye decide karne dena ki usse meaning samajhne ke liye kin dusre words par kitna dhyan dena chahiye.
Self-Attention ek technique/mechanism hai jo Transformer architecture ka core part hai.

LLM ka flow roughly:

Word Embeddings
       ↓
Self-Attention
       ↓
Feed Forward Network
       ↓
Transformer Layers
       ↓
LLM (GPT, Gemini, Claude, etc.)

In [1]:
# NumPy is used for numerical computations and matrix operations
import numpy as np

In [2]:
def softmax(x):
    """
    Converts raw scores into probabilities.

    Example:
    [2, 1, 0] --> [0.66, 0.24, 0.10]

    Properties:
    - All values are between 0 and 1
    - Sum of each row = 1
    """

    # Subtracting max value improves numerical stability
    # and prevents overflow in exp()
    e = np.exp(x - np.max(x, axis=-1, keepdims=True))

    # Divide each value by row sum
    # to convert scores into probabilities
    return e / e.sum(axis=-1, keepdims=True)

In [3]:
def self_attention(Q, K, V):
    """
    Self-Attention Mechanism

    Parameters:
    Q -> Query Matrix
    K -> Key Matrix
    V -> Value Matrix

    Shape:
    (sequence_length, embedding_dimension)

    Returns:
    output  -> Final contextual embeddings
    weights -> Attention weights matrix
    """

    # Dimension of Key vectors
    d_k = Q.shape[-1]

    # -------------------------------
    # STEP 1: Calculate Attention Scores
    # -------------------------------
    #
    # Q @ K.T
    #
    # Matrix multiplication between
    # Query and Key matrices
    #
    # Measures similarity between tokens
    #
    # Shape:
    # (seq_len, seq_len)
    #
    scores = Q @ K.T

    # Scale scores by sqrt(d_k)
    # Prevents extremely large values
    scores = scores / np.sqrt(d_k)

    # -------------------------------
    # STEP 2: Convert Scores to Probabilities
    # -------------------------------
    #
    # Softmax converts scores into
    # attention weights
    #
    weights = softmax(scores)

    # -------------------------------
    # STEP 3: Weighted Sum of Values
    # -------------------------------
    #
    # Each token receives information
    # from all other tokens
    #
    output = weights @ V

    return output, weights

In [4]:
# Fix random seed
# So results remain same every run
np.random.seed(42)

# Number of tokens in sentence
seq_len = 4

# Embedding dimension
d_k = 8

# Create Query Matrix
Q = np.random.randn(seq_len, d_k)

# Create Key Matrix
K = np.random.randn(seq_len, d_k)

# Create Value Matrix
V = np.random.randn(seq_len, d_k)

print("Query Matrix Shape :", Q.shape)
print("Key Matrix Shape   :", K.shape)
print("Value Matrix Shape :", V.shape)

Query Matrix Shape : (4, 8)
Key Matrix Shape   : (4, 8)
Value Matrix Shape : (4, 8)


In [5]:
# Run attention mechanism
output, attn_weights = self_attention(Q, K, V)

print("Output Shape:")
print(output.shape)

print("\nAttention Weights Shape:")
print(attn_weights.shape)

Output Shape:
(4, 8)

Attention Weights Shape:
(4, 4)


In [6]:
print("Attention Weight Matrix:")
print(np.round(attn_weights, 3))

Attention Weight Matrix:
[[0.084 0.255 0.515 0.145]
 [0.641 0.133 0.017 0.209]
 [0.47  0.088 0.111 0.331]
 [0.178 0.492 0.201 0.13 ]]


In [7]:
print("Row sums:")
print(attn_weights.sum(axis=1))

Row sums:
[1. 1. 1. 1.]
